version: 0.2

phases:
  install:
    commands:
      - npm install -g serverless
  pre_build:
    commands:
      - pwd
      - find . -ls
  build:
    commands:
      - serverless deploy --stage $stage
  post_build:
    commands:
      - touch success
artifacts:
  files:
    - success
