version: 0.2

env:
  variables:
    SRC_DIR: src/github.com/tomingtoming/ServerlessPractice

phases:
  install:
    commands:
      - sudo apt-get update
      - sudo apt-get install -y nodejs npm
      - npm config set ca ""
      - npm install -g n
      - n latest
      - npm update -g npm
      - go get -u github.com/golang/dep/cmd/dep
      - npm install -g serverless
  pre_build:
    commands:
      - pwd
      - mkdir -pv /go/src/github.com/tomingtoming/ServerlessPractice/
      - mv * /go/src/github.com/tomingtoming/ServerlessPractice/
      - cd /go/src/github.com/tomingtoming/ServerlessPractice/
      - make
  build:
    commands:
      - serverless deploy --stage $stage
  post_build:
    commands:
      - touch success
artifacts:
  files:
    - /go/src/github.com/tomingtoming/ServerlessPractice/success
  #discard-paths: yes
  #base-directory: location
#cache:
  #paths:
    # - paths
