version: 0.2

phases:
  install:
    commands:
      - go get -u github.com/golang/dep/cmd/dep
  pre_build:
    commands:
      - pwd
      - mkdir -pv /go/src/github.com/tomingtoming/ServerlessPractice/
      - mv * /go/src/github.com/tomingtoming/ServerlessPractice/
      - cd /go/src/github.com/tomingtoming/ServerlessPractice/
  build:
    commands:
      - make
artifacts:
  files:
    - /go/src/github.com/tomingtoming/ServerlessPractice/bin/*
    - /go/src/github.com/tomingtoming/ServerlessPractice/buildspec-deploy.yml
