service: serverless

provider:
  name: aws
  region: ap-northeast-1
  runtime: go1.x
  stage: ${opt:stage, self:custom.defaultStage}

custom:
  defaultStage: dev
  tryo:
    environment:
      dev:
        SLACK_CLIENT_SECRET: ${ssm:TRYO_SLACK_CLIENT_SECRET}
        SLACK_VERIFICATION_TOKEN: ${ssm:TRYO_SLACK_VERIFICATION_TOKEN}
      prd:
        SLACK_CLIENT_SECRET: ${ssm:TRYO_SLACK_CLIENT_SECRET}
        SLACK_VERIFICATION_TOKEN: ${ssm:TRYO_SLACK_VERIFICATION_TOKEN}
  mendes:
    environment:
      dev:
        SLACK_CLIENT_SECRET: ${ssm:MENDES_SLACK_CLIENT_SECRET}
      prd:
        SLACK_CLIENT_SECRET: ${ssm:MENDES_SLACK_CLIENT_SECRET}

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  tryo:
    handler: bin/tryo
    environment: ${self:custom.tryo.environment.${self:provider.stage}}
    events:
      - http:
          path: tryo
          method: post
  mendes:
    handler: bin/mendes
    environment: ${self:custom.mendes.environment.${self:provider.stage}}
    events:
      # 10pm JST every weekday
      - schedule: cron(*/10 0-10 ? * MON-FRI *)
