version: 0.2

env:
  variables:
    GO_BUILD_DIR: "/go/src/github.com/tomingtoming/serverless-practice"

phases:
  pre_build:
    commands:
      - mkdir -pv $GO_BUILD_DIR/
      - mv -v serverless $GO_BUILD_DIR/.
      - cd $GO_BUILD_DIR/serverless/
  build:
    commands:
      - make
  post_build:
    commands:
      - cd ..
      - mv -v serverless $CODEBUILD_SRC_DIR/.
      - cd $CODEBUILD_SRC_DIR
artifacts:
  files:
    - serverless/bin/*
    - serverless/buildspec-deploy.yml
    - serverless/serverless.yml
